#!/bin/sh

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

JIRAWORKLOG_HOME=${JIRAWORKLOG_HOME:-"$SCRIPT_DIR/data/"}

JAR_FILE="$SCRIPT_DIR/lib/jiraworklog.jar"

java -jar "$JAR_FILE" "$JIRAWORKLOG_HOME" "$@"