name: release
env:
  CI: false

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jiraworklog
          path: target/jiraworklog-*.zip

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_PAT }}"

      - name: Create GitHub Release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          RELEASE_NAME="Release $TAG_NAME"
          gh release create $TAG_NAME target/jiraworklog-*.zip --title "$RELEASE_NAME" --notes "Automated release of version $TAG_NAME"
